---
sonet_vault:
  ##
  # default:
  #  sonet_vault['ldap_admin_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['ldap_admin_password']'
  #
  ldap_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36346164316638373866323565633539386137303264373732633865653337333134303764326466
          3236356334663036373235303137646265646132333235610a623435636239336633643762616662
          30353864343465366465333931386266616630653161653731393063646362653466366634636163
          6366303938333039620a313063383931373937333939313061653633363830353961306433663232
          3335
  ##
  # default:
  #  sonet_vault['ldap_config_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['ldap_config_password']'
  #
  ldap_config_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64646530313835366434646562376430626333633432343035373364303363383364643434646132
          3230613262623232356534323239633463653639653233340a373230666466373066636563336631
          33663831376465386363386233663937316439363131356431663835373263653435626330383765
          6461386238626333360a656230386633306332303031393461626638323934393166316465326633
          3663
  ##
  # default:
  #  sonet_vault['ldap_readonly_user_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['ldap_readonly_user_password']'
  #
  ldap_readonly_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34303435373538343333383238376235643931303561653666616135366130346232376261393437
          3965383937346630613234316563303666663235623763350a366132353364326365633734646666
          36366363316362626133363266323735626663663163373534313964306164313130643730653062
          3564643537396231340a343238343833393337323231336439383963626165633939393063616137
          6166
  ##
  # default:
  #  sonet_vault['redmine_admin_mail_account_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['redmine_admin_mail_account_password']'
  #
  redmine_admin_mail_account_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64306133363465363566616463383131623463613661643032383731373934633838616630376463
          6534396637356230306432393966666263316563303139660a393331316438323333336534306530
          35646232623136363264633961613436623461383861326131613635626561373861366133346562
          6332306135333663300a356131653231383330303532643135393461613765386462376433393332
          3030
  ##
  # default:
  #  sonet_vault['gitlab_mail_account_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['gitlab_mail_account_password']'
  #
  gitlab_mail_account_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63333837393930326263333131623933343162373438653166653533373639656138666466303162
          6461643762373232333266666431343538396163353766610a653861623433653561346639323736
          31336362626262626238383166646134313631306339613866336237653336366531663136356232
          6666303839333735380a623838623862376161323265646331383037633539373030333034306536
          6264
  ##
  # default:
  #  sonet_vault['gitlab_root_account_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['gitlab_root_account_password']'
  #
  gitlab_root_account_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35386262393931303330313065643135306636333466326164616539636566663832326538663036
          6261323433633136613237353238353437643139363362380a626433636165636562316439666435
          64623833386233313230623932323962323433306532653134383065306366653866326261343532
          6531616639336539370a326463366164613338663462316237623030656334303164636339363931
          3838
  ##
  # default:
  #  sonet_vault['nextcloud_admin_mail_account_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['nextcloud_admin_mail_account_password']'
  #
  nextcloud_admin_mail_account_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36306236313735613661383137393639663366326531303830616363306164343233333934323538
          6637373961316136336436623931626465616431343931370a373636326262633862313662613939
          64346265626165393331303964306366656463626336656364653665666237373237363062333361
          3437313034343365320a393631336233373632623838306533373132386236663032343066356266
          6437
  ##
  # default:
  #  sonet_vault['ldap_user_default_password']: 'change_me'
  #
  # change it with your vault password:
  #  ansible-vault encrypt_string 'new_password' --name 'sonet_vault['ldap_user_default_password']'
  #
  ldap_user_default_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32353635653733366532623033373638353864653438636434356135616663663461343264653335
          6661333136313534646430363935336236613238333664640a386430623231343134323464633036
          39656539646263383031313464623765383063316132326339303063623533346439633631373734
          3739353535613662390a656664643766613262306538383464653831613539613763326130326336
          6537
