---
mailserv:
  hostname: mail
  domain: "{{ openldap['ldap_domain'] }}"
  ldap_url: "ldap://{{ openldap['ldap_hostname'] }}:389"
  ldap_base_dn: "{{ openldap['ldap_base_dn'] }}"
  ldap_bind_dn: "cn={{ openldap['ldap_readonly_user_username'] }},{{ openldap['ldap_base_dn'] }}"
  ldap_bind_pw: "{{ openldap['ldap_readonly_user_password'] }}"
  ssl_crt_filename: cert.crt
  ssl_key_filename: cert.key
  ssl_ca_crt_filename: ca.crt
  ssl_dhparam_1024: dhparam.pem
  ssl_dhparam_512: dhparam.pem

  backup_cron_exp: 30 4 * * *  # every day at 4:30am
  backup_ttl: 15   # delete backups that are over 15 days
