---
- name: 'caddy : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: caddy
    - service_image_dir: '{{ local_path }}/images/caddy'
    - service_dirs:
        - certs
        - private
        - pki
    - service_gen_certs:
        - "pki.{{ conf['domain'] }}"
        - "gitlab.{{ conf['domain'] }}"
        - "ldapadmin.{{ conf['domain'] }}"
        - "mail.{{ conf['domain'] }}"
        - "mattermost.{{ conf['domain'] }}"
        - "redmine.{{ conf['domain'] }}"
        - "registry.{{ conf['domain'] }}"
        - "storage.{{ conf['domain'] }}"
        - "excalidraw.{{ conf['domain'] }}"
        - "nextcloud.{{ conf['domain'] }}"
        - "onlyoffice.{{ conf['domain'] }}"
        - "drawio.{{ conf['domain'] }}"
        - "portainer.{{ conf['domain'] }}"
        - "adminer.{{ conf['domain'] }}"
        - "grafana.{{ conf['domain'] }}"
    - service_copy_certs:
        - { src: "ca.crt", dest: "certs/ca.crt" }
        - { src: "ca.crt", dest: "pki/ca.crt" }
        - { src: "dh.pem", dest: "certs/dhparam.pem" }
        - { src: "issued/gitlab.{{ conf['domain'] }}.crt", dest: "certs/gitlab.{{ conf['domain'] }}.crt" }
        - { src: "private/gitlab.{{ conf['domain'] }}.key", dest: "private/gitlab.{{ conf['domain'] }}.key" }
        - { src: "issued/mattermost.{{ conf['domain'] }}.crt", dest: "certs/mattermost.{{ conf['domain'] }}.crt" }
        - { src: "private/mattermost.{{ conf['domain'] }}.key", dest: "private/mattermost.{{ conf['domain'] }}.key" }
        - { src: "issued/mail.{{ conf['domain'] }}.crt", dest: "certs/mail.{{ conf['domain'] }}.crt" }
        - { src: "private/mail.{{ conf['domain'] }}.key", dest: "private/mail.{{ conf['domain'] }}.key" }
        - { src: "issued/registry.{{ conf['domain'] }}.crt", dest: "certs/registry.{{ conf['domain'] }}.crt" }
        - { src: "private/registry.{{ conf['domain'] }}.key", dest: "private/registry.{{ conf['domain'] }}.key" }
        - { src: "issued/redmine.{{ conf['domain'] }}.crt", dest: "certs/redmine.{{ conf['domain'] }}.crt" }
        - { src: "private/redmine.{{ conf['domain'] }}.key", dest: "private/redmine.{{ conf['domain'] }}.key" }
        - { src: "issued/ldapadmin.{{ conf['domain'] }}.crt", dest: "certs/ldapadmin.{{ conf['domain'] }}.crt" }
        - { src: "private/ldapadmin.{{ conf['domain'] }}.key", dest: "private/ldapadmin.{{ conf['domain'] }}.key" }
        - { src: "issued/pki.{{ conf['domain'] }}.crt", dest: "certs/pki.{{ conf['domain'] }}.crt" }
        - { src: "private/pki.{{ conf['domain'] }}.key", dest: "private/pki.{{ conf['domain'] }}.key" }
        - { src: "issued/excalidraw.{{ conf['domain'] }}.crt", dest: "certs/excalidraw.{{ conf['domain'] }}.crt" }
        - { src: "private/excalidraw.{{ conf['domain'] }}.key", dest: "private/excalidraw.{{ conf['domain'] }}.key" }
        - { src: "issued/nextcloud.{{ conf['domain'] }}.crt", dest: "certs/nextcloud.{{ conf['domain'] }}.crt" }
        - { src: "private/nextcloud.{{ conf['domain'] }}.key", dest: "private/nextcloud.{{ conf['domain'] }}.key" }
        - { src: "issued/onlyoffice.{{ conf['domain'] }}.crt", dest: "certs/onlyoffice.{{ conf['domain'] }}.crt" }
        - { src: "private/onlyoffice.{{ conf['domain'] }}.key", dest: "private/onlyoffice.{{ conf['domain'] }}.key" }
        - { src: "issued/drawio.{{ conf['domain'] }}.crt", dest: "certs/drawio.{{ conf['domain'] }}.crt" }
        - { src: "private/drawio.{{ conf['domain'] }}.key", dest: "private/drawio.{{ conf['domain'] }}.key" }
        - { src: "issued/portainer.{{ conf['domain'] }}.crt", dest: "certs/portainer.{{ conf['domain'] }}.crt" }
        - { src: "private/portainer.{{ conf['domain'] }}.key", dest: "private/portainer.{{ conf['domain'] }}.key" }
        - { src: "issued/adminer.{{ conf['domain'] }}.crt", dest: "certs/adminer.{{ conf['domain'] }}.crt" }
        - { src: "private/adminer.{{ conf['domain'] }}.key", dest: "private/adminer.{{ conf['domain'] }}.key" }
        - { src: "issued/grafana.{{ conf['domain'] }}.crt", dest: "certs/grafana.{{ conf['domain'] }}.crt" }
        - { src: "private/grafana.{{ conf['domain'] }}.key", dest: "private/grafana.{{ conf['domain'] }}.key" }
  tags: [init, build, push]
